### ISSUE TITLE
Multiple instances, same DOM

### ISSUE THREAD

**Issue by Alphabetus** [jasonmayes/Particle-Engine#1]
First of all, amazing and simple engine.

I was trying to initiate multiple instances of the same engine within same webpage.
Is this something that the engine is prepared for?

I was trying to use the following code to initialize it:
```
jmParticleEngine.init('myCanvas', window.innerWidth, window.innerHeight);
jmParticleEngine.init('myCanvas2', window.innerWidth, window.innerHeight);
```

Apparently it overrides the first instance, therefore ends up with just one canvas "on fire"
Any hints? Or defenitely a no go?

Thank you!

**Comment by jasonmayes** [comment]
That would be a no. I designed this to be in a revealing module design pattern on purpose which means it will always assign itself to the same top level global var.

Is there a reason you need multiple engines? You can make multiple emitters etc...

**Comment by jasonmayes** [comment]
Oh I see multiple canvas. Hmm may need an update to support multiple canvases.

**Comment by jasonmayes** [comment]
I just committed as fix for that. Please try it by adding the optional canvas context you want an emitter to render to using this example code when generating the emitter:

```js
// We can also pass custom Canvas Context if we want to draw to a different canvas.
const customContext = document.getElementById('myCanvas').getContext('2d');

var emit = jmParticleEngine.generateEmitter(Math.ceil(window.innerWidth / 4), Math.ceil(window.innerHeight / 2), 5000, particleGenerator2, customContext);
```

**Comment by Alphabetus** [comment]
Cant make it work.

I have on my markup:
```
<canvas id="myCanvas" class="enemy__fxs"></canvas>
<canvas id="myCanvas2" class="enemy__fxs"></canvas>
```

on JS:
```
jmParticleEngine.init('myCanvas', window.innerWidth, window.innerHeight);

var emit1 = jmParticleEngine.generateEmitter(Math.ceil(window.innerWidth / 2), Math.ceil(window.innerHeight / 2), 1500, particleGenerator5);
emit1.preloadImage('https://storage.googleapis.com/jm-cors/images/fire2.png');

const customContext = document.getElementById('myCanvas2').getContext('2d');
var emit2 = jmParticleEngine.generateEmitter(Math.ceil(window.innerWidth / 2), Math.ceil(window.innerHeight / 2), 5000, particleGenerator5, customContext);

var emitTmp = jmParticleEngine.generateEmitter(Math.ceil((window.innerWidth / 4) * 3), Math.ceil(window.innerHeight / 2), 750, particleGenerator5);

jmParticleEngine.addEmitter(emit1, true);
jmParticleEngine.addEmitter(emit2, true);
jmParticleEngine.addEmitter(emitTmp, true);

setTimeout(function(){
  emitTmp.stop();
}, 5000);
```

What is missing?
Im failing somewhere.

**Comment by jasonmayes** [comment]
Is there any error?
